### ISSUE TITLE
need an option to choose branch

### ISSUE THREAD

**Issue by eallion** [wearerequired/git-mirror-action#3]
need an option to choose branch.
thanks!

**Comment by ocean90** [comment]
Hello @eallion, thanks for the request. Could you please explain your use case for this?

**Comment by eallion** [comment]
Hello, thanks for your reply!
For my case, i can't sync my GitHub repo to my [Gitee](https://gitee.com) repo.
Source: <https://github.com/eallion/eallion.github.io>
Target: <https://gitee.com/eallion/eallion>
BUT the source repo's default branch is `main`, AND i want to sync the `gh-pages` branch.

Now i use the normal shell to sync at: <https://github.com/eallion/eallion.com/blob/main/.github/workflows/main.yml> , it works fine but not perfect.
( Its a Hugo blog site.)

**Comment by ocean90** [comment]
Closing for the same reasons mentioned in #9.
