### ISSUE TITLE
Can't push to remote repository because of wrong host

### ISSUE THREAD

**Issue by tschannik** [wearerequired/git-mirror-action#4]
Hi, 

It looks like the action added the wrong host so it got rejected. Is it possible to add another host?

```
Warning: Permanently added 'github.com,140.82.112.3' (RSA) to the list of known hosts.
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.
```

**Comment by ocean90** [comment]
Hi @tschannik, I'm assuming you are mirroring a GitHub repo to another GitHub repo? It seems like your provided `SSH_PRIVATE_KEY` is either invalid or has no access to the destination repo.

**Comment by tschannik** [comment]
Hi @ocean90 actually i'm trying to mirror the repo to another private bitbucket instance. The provided ssh key should be correct (i should use the private key right?)

**Comment by ocean90** [comment]
Correct, did you add the same key to GitHub (as a deploy key) **and** Bitbucket (in your personal settings)?

**Comment by tschannik** [comment]
Yes

**Comment by ocean90** [comment]
Please double-check everything again. For some reasons the private key provided in the secrets doesn't match with the public key used as a deploy key on GitHub.

**Comment by tschannik** [comment]
Hi, 

First of all, thanks for the fast replies! 
I found the issue.. it was a stupid mistake from my side.
